name: PRINTING IN NYC
favicon: null
layout_spectrum: 0.92766
typography_spectrum: 0.92864
title: Elegant Printing Arts  www.stylishgalleryprint.com  718-749-3520
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.1478716970887035
purpose: []
