name: PRINTING IN NYC
favicon: null
layout_spectrum: 0.34290660824626684
typography_spectrum: 0.8980647090356797
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.25
  lightness: 0.7738397819921374
  saturation: 0.34909278713166714
  rhythmicContrast: 0.1478716970887035
purpose: []
